services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    command: tail -f /dev/null

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mysecretpassword"
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./data:/var/lib/mysql
    command: yes database

  users:
    build: ./users
    command: /bin/sh -c "while true; do echo users; done"